name: vendor
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_animated_splash: ^0.0.10
  flutter_screenutil: ^5.9.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  font_awesome_flutter: ^10.6.0
  progress_state_button: ^1.0.4
  pinput: ^3.0.1
  flutter_hooks: ^0.20.3
  connectivity_plus: ^5.0.2
  firebase_auth: ^4.15.3
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.0
  firebase_storage: ^11.5.6
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  overlay_loading_progress: ^1.0.1
  cached_network_image: ^3.0.0
  cloud_firestore: ^4.13.6
  image_picker: ^1.0.5
  lottie: ^2.7.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding: ^2.1.1
  flutter_blurhash: ^0.8.2
  shrink_sidemenu: ^2.0.0+2-null-safety
  buttons_tabbar: ^1.3.8
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.10
  slide_to_confirm: ^1.1.0
  ionicons: ^0.2.2
  another_stepper: ^1.2.2
  fl_chart: ^0.66.0
  lite_rolling_switch: any
  intl: ^0.18.1
  photo_view: ^0.14.0
  uuid: ^4.2.2
  fluttertoast: ^8.2.4
  motion_toast: ^2.8.0
  blurry_modal_progress_hud: ^1.1.1
  flutter_colorpicker: ^1.0.3
  file_picker: ^6.1.1
  path: ^1.9.0
  flutter_slidable: ^3.0.1
  carousel_slider: ^4.2.1
  flutter_local_notifications: ^17.0.1
  app_settings: ^5.1.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
